# config.yaml

devide:
  id_micro: "RP-1"


# device location
location:
  record: "NOISEPORT-TENERIFE"
  place: "CONTENEDORES"
  point: "P1_CONTENEDORES"


# audio capture parameters
audio:
  format: pyaudio.paInt16
  channels: 1
  sample_rate: 44100
  chunk_size: 11025  # ~1/4 second of audio if RATE=44100
  calibration_constant: -12.08
  window_size: 44100  # window size in samples (1 second if RATE=44100)


# S3
storage:
  s3_bucket_name: "demo-prototype-aac-2025"
  output_wav_folder: "wav_files"
  output_acoust_folder: "acoustic_params"
  output_predict_folder: "predict"
  output_predict_lt_folder: "predictions_litle"


#prediction / DL model settings
prediction:
  yamnet_class_map_csv: yamnet_class_map.csv
  sample_rate: 16000
  chunk_size: 15600  # 0.975 * 16000
  model_tf: "yamnet.h5"
  model_tflt: "yamnet.tflite"
